name: bowser-env
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip>=21.3  # https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/#editable-installation
  - fastapi
  - pydantic>=2.1
  - pyproj>=3.3
  - matplotlib-base
  - numpy>=1.22
  - rasterio>=1.3
  - titiler-core
  - tqdm
  - typing_extensions>=3.10
  - uvicorn
  # # Optional for reading from S3:
  # - s5cmd
  # - boto3
